### ISSUE TITLE
Add VCR-like fixtures to integration tests

### ISSUE THREAD

**Issue by leighmcculloch** [braintree-go/braintree-go#252]

**Comment by tengis617** [comment]
@leighmcculloch is anyone working on this? I'm interested!

**Comment by leighmcculloch** [comment]
@tengis617 I have a WIP progress here: https://github.com/lionelbarrow/braintree-go/compare/add-vcr.

**Comment by leighmcculloch** [comment]
I'm closing this issue as [I have left Braintree](https://twitter.com/___leigh___/status/1146485107881996288) and I'm unable to continue contributing to this library.
