### ISSUE TITLE
New release at new import path

### ISSUE THREAD

**Issue by ccahoon** [braintree-go/braintree-go#264]
First, I'm excited that this module has its own top-level home now. 

We'd love to switch over to this import path, but we would also love it to be on an official version number. Would it reasonable to release a version v0.20.1, or something along those lines, that includes the updates to the official import path and the couple other commits along the way?

This isn't urgent, of course, but I thought I'd mention that it crossed my mind. Cheers!

**Comment by leighmcculloch** [comment]
Good idea! We should tag a new version because the import path is used internally in a couple places. I'll get that out now.

**Comment by leighmcculloch** [comment]
`v0.21.0` is released 👍
