### ISSUE TITLE
CreditCard `product_id` not included on CreditCard type?

### ISSUE THREAD

**Issue by krak3n** [braintree-go/braintree-go#272]
Hi, thank you for producing this library, I was wondering why the `product_id` field is not included on the CreditCard type? https://developers.braintreepayments.com/reference/response/credit-card/python#product_id

Thanks,

Chris

**Comment by leighmcculloch** [comment]
@krak3n I don't think there's any particular reason it hasn't been included other than nobody has added it yet. Would you be up for opening a PR to add this field?

**Comment by krak3n** [comment]
@leighmcculloch certainly :+1: gives me something to do on the train home :train:

**Comment by leighmcculloch** [comment]
The PR for this #274 has been merged. Thanks @krak3n !
