### ISSUE TITLE
(*TransactionGateway).Refund does not support specifying an order ID

### ISSUE THREAD

**Issue by aaronlehmann** [braintree-go/braintree-go#276]
It looks like the Ruby version of the Braintree SDK allows a order ID to be specified as part of creating a refund: https://developers.braintreepayments.com/reference/request/transaction/refund/ruby#order_id

braintree-go does not allow this.

I imagine that this is only a matter of adding an order ID to the `TransactionRequest`. If so, would you like me to open a pull request to do this? And would you like to create a new variant of `Refund` with a different argument list, or modify the existing one in a backward-incompatible way?

**Comment by leighmcculloch** [comment]
Yup we should add this. I think we should add a new function like:

```go
func (*TransactionGateway) RefundWithRequest(context.Context, *TransactionRefundRequest) (*Transaction, error)
```

We'll need a new `TransactionRefundRequest` similar to the Java SDK:
https://github.com/braintree/braintree_java/blob/0676718c89831382d450ee44f4fe8d0389c4c893/src/main/java/com/braintreegateway/TransactionRefundRequest.java

Given that this is an optional field and most people are likely only passing the ID it's probably not worth breaking the existing function.

**Comment by leighmcculloch** [comment]
@aaronlehmann Your welcome to open a PR with this change if you're up for it.

**Comment by leighmcculloch** [comment]
Thanks @aaronlehmann !
