### ISSUE TITLE
Signature-key pair contains the wrong public key!

### ISSUE THREAD

**Issue by viggy28** [braintree-go/braintree-go#279]
Getting that error when trying to use ParseRequest() method.

```
// SubMerchantStatusWebhook is a webhook called by braintree to notify submerchant status
func SubMerchantStatusWebhook(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
	webhookNotificationGateway := &braintree.WebhookNotificationGateway{
		Braintree: common.BraintreeInit(),
	}
	webhookNotification, err := webhookNotificationGateway.ParseRequest(r)
	if err != nil {
		log.Println("ERROR: Parsing webhookNotificationGateway in SubMerchantStatusWebhook()", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	log.Println(webhookNotification.Kind)
}
```

my common.BraintreeInit() is

```
package common

import (
	"log"
	"os"

	braintree "github.com/braintree-go/braintree-go"
)

func BraintreeInit() *braintree.Braintree {
	var env braintree.Environment
	environment := os.Getenv("ENVIRONMENT")
	if environment == "" {
		log.Fatal("FATAL: Braintree environment is not set")
	}
	if environment == "sandbox" {
		env = braintree.Sandbox
	}
	if environment == "production" {
		env = braintree.Production
	}
	//TODO add them in CICD
	merchantID := os.Getenv("MASTERMERCHANTACCOUNTID")
	if merchantID == "" {
		log.Fatal("FATAL: merchantID environment is not set")
	}
	publicKey := os.Getenv("PUBLICKEY")
	if publicKey == "" {
		log.Fatal("FATAL: publicKey environment is not set")
	}
	privateKey := os.Getenv("PRIVATEKEY")
	if merchantID == "" {
		log.Fatal("FATAL: privateKey environment is not set")
	}
	braintree := braintree.New(env, merchantID, publicKey, privateKey)
	return braintree
}
```

Not sure am i doing anything wrong here. Checked the keys & merchantId everything looks fine. Thanks.

**Comment by leighmcculloch** [comment]
Hi @vr001! Are you able to share some of the details of the error that's being returned by `webhookNotificationGateway.ParseRequest(...)`?

**Comment by leighmcculloch** [comment]
This error usually happens if the webhook is configured if the public key configured with the SDK doesn't match any of the keys used to sign the webhook. If you look at the raw signature included in the webhook the signatures will be separated by `&`, with one per key. There might only be one. Within a signature there will be two parts separated by the `|`. The first part is the public key. Do you see a signature matching your public key? You might have multiple users in your account and the webhook might be configured with a different user.

**Comment by viggy28** [comment]
@leighmcculloch Thanks for the response.

Error i am getting: `Signature-key pair does not contain |`

Here is the code. Of course, removed the public & private key.

`// SubMerchantStatusWebhook is a webhook called by braintree to notify submerchant status
func SubMerchantStatusWebhook(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		w.WriteHeader(http.StatusMethodNotAllowed)
	}
	bt := braintree.New(braintree.Sandbox, "merchantId", "pubkey", "pvtkey")
	webhookNotificationGateway := bt.WebhookNotification()
	webhookNotification, err := webhookNotificationGateway.ParseRequest(r)
	if err != nil {
		log.Println("ERROR: Parsing webhookNotificationGateway in SubMerchantStatusWebhook()", err)
		w.WriteHeader(http.StatusInternalServerError)
		return
	}
	log.Println(webhookNotification.Kind)
}
`

Am i doing something wrong? 

I checked the user, there is only one user. Thanks.

**Comment by leighmcculloch** [comment]
@viggy28 nothing jumps out at me in the examples you shared, although the fact that you are seeing different errors suggests that something is changing. Initially you reported `Signature-key pair contains the wrong public key!` but now `Signature-key pair does not contain |`. Is it possible the request is being altered before it gets to this code?

**Comment by viggy28** [comment]
@leighmcculloch you are spot on. Was using bytes.NewBuffer() on the request.Body. So, it modified the body. Am closing the issue. Sorry, for creating it. Appreciate your efforts.

**Comment by leighmcculloch** [comment]
Yay! I'm glad that we figured it out. Happy coding!
